name: cron_parser
description: "Cron parser for Dart."
version: 1.0.0
repository: https://github.com/ilhamft/cron_parser
homepage: https://github.com/ilhamft/cron_parser

topics:
  - cron
  - cron-parser
  - cron-time

environment:
  sdk: ">=3.3.2 <4.0.0"

dev_dependencies:
  test: ^1.24.9
